# Generated by Django 3.0.3 on 2020-05-16 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='key',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
