# Generated by Django 3.0.3 on 2020-05-21 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decrypt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decode',
            old_name='deco',
            new_name='encrpyted_password',
        ),
    ]
