# Generated by Django 3.0.3 on 2020-05-21 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decrypt', '0002_auto_20200521_0844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decode',
            old_name='encrpyted_password',
            new_name='encrypted_password',
        ),
    ]
