# Generated by Django 3.0.3 on 2020-05-18 10:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('encrypt', '0002_auto_20200518_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encoded',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
