# Generated by Django 3.0.3 on 2020-05-19 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('encrypt', '0003_auto_20200518_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encoded',
            name='enc',
        ),
        migrations.RemoveField(
            model_name='encoded',
            name='user',
        ),
        migrations.AddField(
            model_name='encoded',
            name='hasher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
