# Generated by Django 3.0.3 on 2020-05-19 02:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('encrypt', '0004_auto_20200519_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='encoded',
            name='enc',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
